FROM ubuntu:18.04

## add some labels
LABEL maintainer="hantsawilliams@gmail.com"
LABEL version="0.1"
LABEL description="This is a Dockerfile for a simple Ubuntu container."

## update the container
RUN apt-get update && apt-get upgrade -y